name: Issue Report
description: File a report for something not working correctly.
title: "[Issue]: "

body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this report!

      On a Linux system, you can acquire your OS, CPU, GPU, and ROCm version (for filling out this report) with the following commands:
      echo "OS:" && cat /etc/os-release | grep -E "^(NAME=|VERSION=)";
      echo "CPU: " && cat /proc/cpuinfo | grep "model name" | sort --unique;
      echo "GPU:" && /opt/rocm/bin/rocminfo | grep -E "^\s*(Name|Marketing Name)";
      echo "ROCm in /opt:" && ls -1 /opt | grep -E "rocm-";
- type: textarea
  attributes:
    label: Problem Description
    description: Describe the issue you encountered.
    placeholder: "The steps to reproduce can be included here, or in the dedicated section further below."
  validations:
    required: true
- type: input
  attributes:
    label: Operating System
    description: What is the name and version number of the OS?
    placeholder: "e.g. Ubuntu 22.04.3 LTS (Jammy Jellyfish)"
  validations:
    required: true
- type: input
  attributes:
    label: CPU
    description: What CPU did you encounter the issue on?
    placeholder: "e.g. AMD Ryzen 9 5900HX with Radeon Graphics"
  validations:
    required: true
- type: dropdown
  attributes:
    label: GPU
    description: What GPU(s) did you encounter the issue on?
    multiple: true
    options:
        - AMD Instinct MI250X
        - AMD Instinct MI250    
        - AMD Instinct MI210    
        - AMD Instinct MI100    
        - AMD Instinct MI50     
        - AMD Instinct MI25     
        - AMD Radeon Pro W7900  
        - AMD Radeon Pro W6800  
        - AMD Radeon Pro V620   
        - AMD Radeon Pro VII    
        - AMD Radeon RX 7900 XTX
        - AMD Radeon VII        
        - AMD Radeon Pro W7900  
        - AMD Radeon Pro W7800  
        - AMD Radeon Pro W6800  
        - AMD Radeon Pro W6600
        - AMD Radeon Pro W5500
        - AMD Radeon Pro VII
        - AMD Radeon RX 7900 XT
        - AMD Radeon RX 7600
        - AMD Radeon RX 6950 XT
        - AMD Radeon RX 6900 XT
        - AMD Radeon RX 6800 XT
        - AMD Radeon RX 6800
        - AMD Radeon RX 6750
        - AMD Radeon RX 6700 XT
        - AMD Radeon RX 6700
        - AMD Radeon RX 6650 XT
        - AMD Radeon RX 6600 XT
        - AMD Radeon RX 6600
        - Other
  validations:
    required: true
  validations:
    required: true
- type: input
  attributes:
      label: Other
      description: If other please specify
  validations:
  required: true
- type: dropdown
  attributes:
    label: ROCm Version
    description: What version(s) of ROCm did you encounter the issue on?
    multiple: true
    options:
        - ROCm 5.7.1
        - ROCm 5.7.0
        - ROCm 5.6.2
        - ROCm 5.6.8
  validations:
    required: true
- type: input
  attributes:
    label: ROCm Component
    description: (Optional) If this issue relates to a specific ROCm component, it can be mentioned here.
    placeholder: "e.g. rocBLAS"

- type: textarea
  attributes:
    label: Steps to Reproduce
    description: (Optional) Detailed steps to reproduce the issue.
    placeholder: Please also include what you expected to happen, and what actually did, at the failing step(s).
  validations:
    required: false

- type: textarea
  attributes:
    label: Output of /opt/rocm/bin/rocminfo --support
    description: The output of rocminfo --support will help to better address the problem.
    placeholder: |
      ROCk module is loaded
      =====================
      HSA System Attributes
      =====================
      [...]
  validations:
    required: true
