name: Issue retrieval

on:
  issues:
    types: [opened]

jobs:
  auto-retrieve:
    permissions: 
        issues: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Retrieve Issue'
        uses: abhimeda/rocm_issue_management@v1.8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          
