name: Issue retrieval

on:
  issues:
    types: [opened]

jobs:
  auto-retrieve:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
      - name: 'Retrieve Issue'
        uses: temporarysupersecretorganization/private_action@main
        with:
          authentication-token: ${{ steps.generate_token.outputs.token }}
          github-organization: 'temporarysupersecretorganization'
          github-repo: 'tempfortesting'
          
          
