name: Add Issues to Project

on:
  issues:
    types:
      - opened  # You can customize this trigger as needed

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    
    steps:
    - name: Add to Project
      uses: actions/github-script@0.7.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue = github.context.payload.issue;
          await github.projects.createCard({
            column_id: COLUMN_ID,  // Replace with your column ID
            content_id: issue.id,
            content_type: "Issue"
          });
